TravelerPortal.WebUI/Controllers/EventsController.cs
using System.Linq;
using System.Web.Mvc;
using TravelerPortal.Services;
using TravelerPortal.WebUI.Views.Events;

namespace TravelerPortal.WebUI.Controllers
{
    public class EventsController : Controller
    {
        [ChildActionOnly]
        public PartialViewResult EventsSidebar()
        {
            var eventsList = EventsService.GetActive().OrderByDescending(e => e.StartDate).ToArray();
            return PartialView(eventsList);
        }

        public ActionResult Schedule()
        {
            ViewBag.ActiveMainMenuItemTitle = "Расписание";
            var activeEvents = EventsService.GetActive();
            var model = new ScheduleVM();
            foreach (var _event in activeEvents)
            {
                model.Events.Add(new EventVM()
                {
                    StartDate = _event.StartDate,
                    EndDate = _event.EndDate,
                    Price_UAH_ = _event.Price_UAH_,
                    Name = _event.Name,
                    AmountOfDays = (_event.EndDate - _event.StartDate).Days,
                    Url = Url.RouteUrl("TravelById", new { travelId = _event.TravelId })
                });
            }
            return View(model);
        }
    }
}

TravelerPortal.WebUI/Controllers/NewsController.cs
using System.Web.Mvc;
using TravelerPortal.Services;

namespace TravelerPortal.WebUI.Controllers
{
    public class NewsController : Controller
    {
        private NewsService newsService;

        public NewsController()
        {
            newsService = new NewsService();
            ViewBag.ActiveMainMenuItemTitle = "Новости";
        }

        public ActionResult NewsMiddle()
        {
            var newsList = newsService.GetActive();
            return View(newsList);
        }

        [ChildActionOnly]
        public PartialViewResult NewsSidebar()
        {
            var newsList = newsService.GetActive();
            return PartialView(newsList);
        }

        public ActionResult News(int newsId)
        {
            var news = newsService.GetById(newsId);
            return View(news);
        }
    }
}

TravelerPortal.WebUI/Controllers/PhotogalleryController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using TravelerPortal.Services;
using TravelerPortal.WebUI.Views.Photogallery;

namespace TravelerPortal.WebUI.Controllers
{
    public class PhotogalleryController : Controller
    {
        public PhotogalleryController()
        {
            ViewBag.ActiveMainMenuItemTitle = "Фотогалерея";
        }

        public ActionResult Albums()
        {
            var albums = PhotogalleryService.GetActiveAlbums();
            var model = new AlbumsVM();
            model.Albums = albums.Select(a => new TravelerPortal.WebUI.Models.Photogallery.Album
            {
                Id = a.Id,
                Name = a.Name,
                CoverPath = a.CoverPath
            }).ToList();
            return View(model);
        }



        public ActionResult Album(int albumId)
        {
            var album = PhotogalleryService.GetAlbumWithImages(albumId);
            var albumImages = album.AlbumImages
                .Select(ai => new TravelerPortal.WebUI.Models.Photogallery.AlbumImage
                {
                    Id = (int)ai.Id,
                    Name = ai.Name,
                    Description = ai.Description,
                    ThumbPath = ai.Path,
                    ThumbnailPath = ai.Thumbnail
                }).ToList();
            var model = new AlbumVM
            {
                Name = album.Name,
                Images = albumImages
            };
            return View(model);
        }

        [ChildActionOnly]
        public PartialViewResult RandomAlbumsPicturesHeader()
        {
            var dbActiveAlbums = PhotogalleryService.GetActiveAlbums("AlbumImages");
            var model = new RandomAlbumsPicturesHeaderVM()
            {
                Images = (from dbAlbum in dbActiveAlbums
                          let randomAlbumImage = dbAlbum.AlbumImages.ToArray()[new Random().Next(1, dbAlbum.AlbumImages.Count())]
                          select new RandomAlbumThumbnailVM()
                          {
                              AlbumId = (int)dbAlbum.Id,
                              AlbumImageId = (int)randomAlbumImage.Id,
                              Thumbnail = randomAlbumImage.Thumbnail
                          })
                          .ToList()
            };
            return PartialView(model);
        }
    }
}

TravelerPortal.WebUI/Controllers/TimezoneCookieAdderController.cs
using System.Web.Mvc;

namespace TravelerPortal.WebUI.Controllers
{
    public class TimezoneCookieAdderController : Controller
    {
        public ActionResult TimezoneCookieAdder()
        {
            return View();
        }
    }
}

TravelerPortal.WebUI/Views/Shared/TimezoneCookieAdder.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
    <head>
        <title></title>
        <script src="//code.jquery.com/jquery-1.10.2.min.js"></script>
        <script src="~/Content/js/jquery.cookie.js"></script>
        <script>
            $(function () {
                $.cookie("timeZoneOffset", new Date().getTimezoneOffset() * -1, { path: "/" });
                document.location = "@Request.QueryString["redirectUrl"]";
            });
        </script>
    </head>
<body>
    Please, wait for a while
    We are getting information about your time zone
</body>
</html>

TravelerPortal.WebUI/Views/Shared/_Layout.cshtml
@using TravelerPortal.WebUI.Helpers
@using TravelerPortal.Services
@{
    var randomQuote = QuotesService.GetRandom();
    var randomOpinion = OpinionsService.GetRandom();
}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Soul&nbsp;Travel</title>
    <link rel="shortcut icon" type="image/x-icon" href="~/favicon.ico" />
    @RenderStyles()
    @RenderHeaderScripts()
</head>
<body>
    <div id="wrap">
        <div id="header">
            <div class="picture-film">
                @{ Html.RenderAction("RandomAlbumsPicturesHeader", "Photogallery", new { area = string.Empty }); }
            </div>
            <div class="opinion">
                <img class="photo" src="@randomOpinion.Thumbnail">
                <div class="response">@randomOpinion.Text</div>
            </div>
        </div>
        <div id="content-wrap">
            <a href="~/" class="logo-link">
                <h1 id="logo"><span class="green">soul</span>travel</h1>
                <h2 id="slogan">путешествия со смыслом<br>
                    путешествия для души</h2>
            </a>
            <img src="~/Content/img/headerphoto.jpg" class="no-border" />
            <div id="sidebar">
                <ul class="sidemenu">
                    @Html.BuildMainMenuItems(Url, (string)ViewBag.ActiveMainMenuItemTitle)
                </ul>
                <div class="wise-words">
                    <p>&quot;@randomQuote.Text&quot;</p>
                    <div class="author">@randomQuote.Author</div>
                </div>
            </div>
            <div id="main">
                @RenderBody()
            </div>
            <div id="rightbar">
                <h1>Новости</h1>
                @{ Html.RenderAction("NewsSidebar", "News", new { area = string.Empty }); }
                <h1>Мероприятия<a href="@Url.RouteUrl("EventSchedule")" style="float: right; font-size: 12px; color: cornflowerblue; text-decoration: underline; line-height: 23px;">расписание</a></h1>
                @{ Html.RenderAction("EventsSidebar", "Events", new { area = string.Empty }); }
            </div>
        </div>
        <div id="footer">
            <div class="footer-left">
                <p class="align-left">&copy;&nbsp;2013&nbsp;<strong>Soul&nbsp;Travel</strong></p>
            </div>
            <div class="footer-right">
                @* TODO: appropriate links here
                    <p class="align-right"><a href="javascript:void(0)">Home</a>&nbsp;|&nbsp; <a href="javascript:void(0)">SiteMap</a>&nbsp;|&nbsp; <a href="javascript:void(0)">RSS Feed</a> </p>
                *@
            </div>
        </div>
    </div>
    @RenderFooterScripts()
</body>
</html>

@helper RenderStyles()
{
    <link rel="stylesheet" type="text/css" href="~/Content/css/reset.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/css/base.css" />
    @RenderSection("Styles", false)
}

@helper RenderHeaderScripts()
{
    <script src="~/Content/js/jquery-1.10.2.min.js"></script>
    <script src="~/Content/js/jquery.cookie.js"></script>
    <script>
        $.cookie("timeZoneOffset", new Date().getTimezoneOffset() * -1, { path: "/" });
    </script>
    @RenderSection("HeaderScripts", false)
}

@helper RenderFooterScripts()
{
    <script>
        function notImplemented() {
            alert("Извините за неудобства. Находится в разработке.");
        };
        function stringifyDateTime(datetime) {
            var addLeadingZeroSymbolIfNeeded = function (number) {
                if (number < 10) {
                    return "0" + number;
                } else {
                    return number;
                }
            };
            var strDate = datetime.getFullYear() + "-" + addLeadingZeroSymbolIfNeeded((datetime.getMonth() + 1)) + "-" + addLeadingZeroSymbolIfNeeded(datetime.getDate());
            var strTime = addLeadingZeroSymbolIfNeeded(datetime.getHours()) + ":" + addLeadingZeroSymbolIfNeeded(datetime.getMinutes());
            return strDate + " " + strTime;
        };
        var server = {
            configurations: {},
            routeUrls: {}
        };
    </script>
    @RenderSection("FooterScripts", false)
}